/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Atomquest Video Calling Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface LoginInput {
  username: string;
  password: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  agent: 'agent',
  customer: 'customer',
  admin: 'admin',
} as const;

export interface User {
  id: number;
  username: string;
  role: UserRole;
  displayName: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export type SessionStatus = typeof SessionStatus[keyof typeof SessionStatus];


export const SessionStatus = {
  waiting: 'waiting',
  active: 'active',
  ended: 'ended',
} as const;

export interface Session {
  id: string;
  title: string;
  status: SessionStatus;
  agentId: number;
  agentName: string;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  inviteToken?: string | null;
  /** @nullable */
  startedAt?: string | null;
  /** @nullable */
  endedAt?: string | null;
  createdAt: string;
}

export interface SessionInput {
  title: string;
}

export type SessionDetailStatus = typeof SessionDetailStatus[keyof typeof SessionDetailStatus];


export const SessionDetailStatus = {
  waiting: 'waiting',
  active: 'active',
  ended: 'ended',
} as const;

export interface SessionDetail {
  id: string;
  title: string;
  status: SessionDetailStatus;
  agentId: number;
  agentName: string;
  /** @nullable */
  customerName?: string | null;
  /** @nullable */
  startedAt?: string | null;
  /** @nullable */
  endedAt?: string | null;
  createdAt: string;
  messageCount: number;
  /** @nullable */
  durationSeconds?: number | null;
}

export interface InviteResponse {
  token: string;
  inviteUrl: string;
}

export interface ChatMessage {
  id: number;
  sessionId: string;
  senderId: number;
  senderName: string;
  senderRole: string;
  content: string;
  createdAt: string;
}

export interface AdminStats {
  totalSessions: number;
  activeSessions: number;
  endedSessions: number;
  waitingSessions: number;
  totalMessages: number;
}

